include theos/makefiles/common.mk

TWEAK_NAME = GoogiriSiriActivator
GoogiriSiriActivator_FILES = Tweak.xm
GoogiriSiriActivator_FRAMEWORKS = UIKit
GoogiriSiriActivator_LDFLAGS = -lactivator

include $(THEOS_MAKE_PATH)/tweak.mk
